#!/usr/bin/env bash

main() {
  if [ "$1" == "" ]; then
    tree -aCilv --noreport --filesfirst -- /
  elif [ "$2" != "" ]; then
    tree -aCilv --noreport --filesfirst -- "$1" | grep -i "$2"
  else
    tree -aCilv --noreport --filesfirst -- "$1"
  fi
}

main "$@"
