#!/usr/bin/env bash

if [ "$1" == "" ]; then
    printf "Usage: bashescal <argument> e.g. 'bashescal doas'"; exit 1
fi

if [ "$privE" == "$1" ]; then
    printf "The privilege escalation tool is already set to %s", "$1"
else
    lineNum=$(grep -n 'export privE=' $HOME/.bashrc | awk -F ':' '{print $1}') # Returns the line that 'export privE=' is found
    if [ "$lineNum" == "" ] || [ $lineNum -lt 1 ]; then
        exit 1
    fi
    sed -i "${lineNum}s/.*/privE=\"${1}\"/" "$HOME/.bashrc" # Replace the line that the 'privE' variable is defined
    source $HOME/.bashrc
fi