#!/usr/bin/env bash
fail() {
  printf "an error has occured, please refer to the terminal output"
  exit
}
kdeMainBak() {
  mkdir ./dkdeBak || fail
  cd ./dkdeBak || fail
  cp -rv $HOME/.config/kdeconnect ./ || fail
  cp -rv $HOME/.config/k* ./ || fail
  cp -rv $HOME/.config/plasma* ./
  cd ../ || fail
}

kdeArchiveCreate() {
  tar -jcvf ./dkdeBak dKdeBackup.tar.bz2 || printf "archiving failed, exiting..." && fail
  location="$(pwd)/dKdeBackup.tar.bz2"
  rm -rf ./dkdeBak || fail
  printf "the compressed archive backup is located at %s", $location
  printf "archive finished..."
}
kdeBackup() {
  kdeMainBak
  kdeArchiveCreate
printf "finished"
}


while true; do
  read -p "Do you want to backup KDE? [Y/n] " yn
  case $yn in
    [Yy]* ) kdeBackup;;
    [Nn]* ) exit 0;;
    "" ) kdeBackup;;
    * ) echo "Please answer yes or no.";;
  esac
done