#! /usr/bin/env bash
cpIso() {
  mkdir /tmp/image
  sudo mount  $1 /tmp/image -o ro,loop -t iso9660
  cp /tmp/image/* ./image
  sudo umount /tmp/image
}

if [ -f "$1" ] ; then
  case $1 in
    *.tar.bz2)   tar xjf $1    ;;
    *.tar.gz)    tar xzf $1    ;;
    *.bz2)       bunzip2 $1    ;;
    *.rar)       unrar x $1    ;;
    *.gz)        gunzip $1     ;;
    *.tar)       tar xf $1     ;;
    *.tbz2)      tar xjf $1    ;;
    *.tgz)       tar xzf $1    ;;
    *.zip)       unzip $1      ;;
    *.Z)         uncompress $1 ;;
    *.7z)        7z x $1       ;;
    *.deb)       ar x $1       ;;
    *.tar.xz)    tar xf $1     ;;
    *.tar.zst)   unzstd $1     ;;
    *.xz)        xz -d $1      ;;
    *.shar)      unshar $1     ;;
    *.iso)       cpIso         ;;
    *)           echo -e "'$1' cannot be extracted via extract. please do so manually.\n" ;;
  esac
else
  echo -e "'$1' is not a valid file \n"
fi

