#!/usr/bin/env bash

shells="$(awk -F "/" '/^\// {print $NF}' /etc/shells | uniq)"
echo $shells
inshells="$(echo "${shells}" | grep -i $1)"
echo "$inshells"

if [ "$1" == "powershell"]; then
  1="pwsh"
fi

if [ "${inshells}" == "" ]; then
  printf "error: the selected shell in not found in '/etc/shells"
  exit 1
else
    chsh $(which "${1}")
    printf "finished"
    exit 0
fi