#!/usr/bin/env zsh
# ______ _____ _    _ ______  _____  _____          _      
#|___  // ____| |  | |  ____|/ ____|/ ____|   /\   | |      AUTHOR:  Decator
#   / /| (___ | |__| | |__  | (___ | |       /  \  | |      WEBSITE: https://el-wumbus.github.io/
#  / /  \___ \|  __  |  __|  \___ \| |      / /\ \ | |      DISCORD: https://discord.gg/8wBUFeGGYc
# / /__ ____) | |  | | |____ ____) | |____ / ____ \| |____  GITHUB:  https://github.com/El-Wumbus
#/_____|_____/|_|  |_|______|_____/ \_____/_/    \_\______|
# NAME: zshescal
# DESCRIPTION: changes the privilege escalation tool in the zshrc when using the variable $privE,
# this is done in my(decator) configs
# verison 0.1.0 TESTING                                                         

if [ "$1" == "" ]; then
    printf "Usage: bashescal <argument> e.g. 'bashescal doas'"; exit 1
fi

if [ "$privE" == "$1" ]; then
    printf "The privilege escalation tool is already set to %s", "$1"
else
    lineNum=$(grep -n 'export privE=' $HOME/.zshrc | awk -F ':' '{print $1}') # Returns the line that 'export privE=' is found
    if [ "$lineNum" == "" ] || [ $lineNum -lt 1 ]; then
        echo "export privE='$1'" >> $HOME/.zshrc # If the variable declaration isnt found in in the zshrc then it will append the line and exit.
        exit 0
    fi
    sed -i "${lineNum}s/.*/privE=\"${1}\"/" "$HOME/.zshrc" # Replace the line that the 'privE' variable is defined
    source $HOME/.zshrc
fi